# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT

# @todo #1326:30min Enable only necessary tests. Several checks
#  are not available for the project. For example a lot of
#  package name contains capital letter and such names are conventional.
---
exclude_paths:
  - "src/test/groovy/*.groovy"
  - "eo-runtime/src/test/java/integration/PhiUnphiIT.java"
  - "eo-maven-plugin/src/test/java/org/eolang/maven/AssembleMojoIT.java"
  - "eo-maven-plugin/src/test/java/org/eolang/maven/LintMojoTest.java"
  - "eo-maven-plugin/src/test/java/org/eolang/maven/LintMojoIT.java"
