# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: phi-sample
'on':
  push:
    branches:
      - master
jobs:
  phi-sample:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p gh-pages
          cp eo-parser/src/test/resources/org/eolang/parser/phi-syntax/all-the-basics.phi gh-pages/sample.phi
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
